import "../globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import QueryProvider from "@/components/providers/QueryProvider";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { getSession } from "@/features/auth/session";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();

  return (
    <html lang="en">
      <QueryProvider>
        <AuthProvider initUser={user}>
          <body className={`${manrope.variable} antialiased w-full relative`}>
            <main>{children}</main>
          </body>
        </AuthProvider>
      </QueryProvider>
    </html>
  );
}
