import "../globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import QueryProvider from "@/components/providers/QueryProvider";
import { getSession } from "@/features/auth/session";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { AuthProvider } from "@/components/providers/AuthProvider";
import CheckoutProvider from "@/features/checkout/components/CheckoutProvider";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Audio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSession();

  console.log("User in RootLayout: ", user);

  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased w-full relative`}>
        <QueryProvider>
          <AuthProvider initUser={user}>
            <CheckoutProvider>
              <Header />
              <main className="pt-[12rem] w-full flex flex-col gap-[12rem] lg:gap-[16.8rem] px-[2.4rem] lg:px-[4rem] mb-[12rem] lg:mb-[20rem]">
                {children}
              </main>
              <Footer />
            </CheckoutProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
