import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
// import { getSession } from "@/features/auth/session";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await getSession();

  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased w-full relative`}>
        <Header />
        <QueryProvider>
          <main>{children}</main>
        </QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
